import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { SYSTEM_SLOT_DEFINITIONS } from '@netior/shared/constants';
import type { SystemSlotKey } from '@netior/shared/types';
import {
  createArchetypeField,
  deleteArchetypeField,
  listArchetypeFields,
  reorderArchetypeFields,
  updateArchetypeField,
} from '../netior-service-client.js';
import { emitChange } from '../events.js';
import { registerNetiorTool } from './shared-tool-registry.js';

const fieldTypeSchema = z.enum([
  'text',
  'textarea',
  'number',
  'boolean',
  'date',
  'datetime',
  'select',
  'multi-select',
  'radio',
  'relation',
  'file',
  'url',
  'color',
  'rating',
  'tags',
  'archetype_ref',
]);

const systemSlotKeys = new Set(SYSTEM_SLOT_DEFINITIONS.map((definition) => definition.key));
const systemSlotSchema = z.string().refine(
  (value) => systemSlotKeys.has(value as never),
  'Invalid system slot key',
);

export function registerArchetypeFieldTools(server: McpServer): void {
  registerNetiorTool(
    server,
    'list_archetype_fields',
    { archetype_id: z.string().describe('The archetype ID') },
    async ({ archetype_id }) => {
      try {
        const result = await listArchetypeFields(archetype_id);
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  registerNetiorTool(
    server,
    'create_archetype_field',
    {
      archetype_id: z.string().describe('The archetype ID'),
      name: z.string().describe('Field name'),
      field_type: fieldTypeSchema.describe('Field type'),
      sort_order: z.number().describe('Field order index'),
      required: z.boolean().optional().describe('Whether the field is required'),
      default_value: z.string().optional().describe('Default value'),
      options: z.string().optional().describe('Comma-separated inline options for select-like fields'),
      ref_archetype_id: z.string().optional().describe('Referenced archetype ID for archetype_ref fields'),
      system_slot: systemSlotSchema.nullable().optional().describe('Optional system slot key or null'),
      slot_binding_locked: z.boolean().optional().describe('Whether the system slot binding is locked'),
      generated_by_trait: z.boolean().optional().describe('Whether this field was generated by an archetype trait'),
    },
    async ({
      archetype_id,
      name,
      field_type,
      sort_order,
      required,
      default_value,
      options,
      ref_archetype_id,
      system_slot,
      slot_binding_locked,
      generated_by_trait,
    }) => {
      try {
        const result = await createArchetypeField({
          archetype_id,
          name,
          field_type,
          sort_order,
          required,
          default_value,
          options,
          ref_archetype_id,
          system_slot: system_slot as SystemSlotKey | null | undefined,
          slot_binding_locked,
          generated_by_trait,
        });
        emitChange({ type: 'archetypeField', action: 'create', id: result.id });
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  registerNetiorTool(
    server,
    'update_archetype_field',
    {
      field_id: z.string().describe('The field ID to update'),
      name: z.string().optional().describe('New field name'),
      field_type: fieldTypeSchema.optional().describe('New field type'),
      sort_order: z.number().optional().describe('New field order index'),
      required: z.boolean().optional().describe('Whether the field is required'),
      default_value: z.string().nullable().optional().describe('New default value'),
      options: z.string().nullable().optional().describe('New comma-separated inline options'),
      ref_archetype_id: z.string().nullable().optional().describe('Referenced archetype ID or null'),
      system_slot: systemSlotSchema.nullable().optional().describe('New system slot key or null'),
      slot_binding_locked: z.boolean().optional().describe('Whether the system slot binding is locked'),
      generated_by_trait: z.boolean().optional().describe('Whether this field was generated by an archetype trait'),
    },
    async ({
      field_id,
      name,
      field_type,
      sort_order,
      required,
      default_value,
      options,
      ref_archetype_id,
      system_slot,
      slot_binding_locked,
      generated_by_trait,
    }) => {
      try {
        const result = await updateArchetypeField(field_id, {
          name,
          field_type,
          sort_order,
          required,
          default_value,
          options,
          ref_archetype_id,
          system_slot: system_slot as SystemSlotKey | null | undefined,
          slot_binding_locked,
          generated_by_trait,
        });
        if (!result) {
          return {
            content: [{ type: 'text' as const, text: `Error: Archetype field not found: ${field_id}` }],
            isError: true,
          };
        }
        emitChange({ type: 'archetypeField', action: 'update', id: field_id });
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  registerNetiorTool(
    server,
    'delete_archetype_field',
    { field_id: z.string().describe('The field ID to delete') },
    async ({ field_id }) => {
      try {
        const deleted = await deleteArchetypeField(field_id);
        if (!deleted) {
          return {
            content: [{ type: 'text' as const, text: `Error: Archetype field not found: ${field_id}` }],
            isError: true,
          };
        }
        emitChange({ type: 'archetypeField', action: 'delete', id: field_id });
        return {
          content: [{ type: 'text' as const, text: JSON.stringify({ success: true, id: field_id }) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  registerNetiorTool(
    server,
    'reorder_archetype_fields',
    {
      archetype_id: z.string().describe('The archetype ID'),
      ordered_ids: z.array(z.string()).describe('Field IDs in the desired order'),
    },
    async ({ archetype_id, ordered_ids }) => {
      try {
        const success = await reorderArchetypeFields(archetype_id, ordered_ids);
        return {
          content: [{ type: 'text' as const, text: JSON.stringify({ success, archetype_id, ordered_ids }, null, 2) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );
}
