import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import type { FieldMeaningBindingKey } from '@netior/shared/types';
import {
  createSchemaField,
  deleteSchemaField,
  listSchemaFields,
  reorderSchemaFields,
  updateSchemaField,
} from '../netior-service-client.js';
import { emitChange } from '../events.js';
import { registerNetiorTool } from './shared-tool-registry.js';
import { fromAgentFieldType, toAgentSchemaField, type AgentFieldType } from './schema-surface.js';

const fieldTypeSchema = z.enum([
  'text',
  'textarea',
  'number',
  'boolean',
  'date',
  'datetime',
  'select',
  'multi-select',
  'radio',
  'relation',
  'file',
  'url',
  'color',
  'rating',
  'tags',
  'schema_ref',
]);

const meaningBindingSchema = z.string().regex(
  /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/,
  'Meaning binding keys must be dotted lowercase paths such as time.due or temporal.deadline',
);

export function registerSchemaFieldTools(server: McpServer): void {
  registerNetiorTool(
    server,
    'list_schema_fields',
    { schema_id: z.string().describe('The schema ID') },
    async ({ schema_id }) => {
      try {
        const result = (await listSchemaFields(schema_id)).map(toAgentSchemaField);
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  registerNetiorTool(
    server,
    'create_schema_field',
    {
      schema_id: z.string().describe('The schema ID'),
      name: z.string().describe('Field name'),
      field_type: fieldTypeSchema.describe('Field value type'),
      sort_order: z.number().describe('Field order index'),
      required: z.boolean().optional().describe('Whether the field is required'),
      default_value: z.string().optional().describe('Default value'),
      options: z.string().optional().describe('Comma-separated inline options for select-like fields'),
      ref_schema_id: z.string().optional().describe('Referenced schema ID for schema_ref fields'),
      meaning_bindings: z.array(meaningBindingSchema).optional().describe('Optional semantic meaning bindings for this field'),
      generated_by_model: z.boolean().optional().describe('Whether this field was generated by a model'),
    },
    async ({
      schema_id,
      name,
      field_type,
      sort_order,
      required,
      default_value,
      options,
      ref_schema_id,
      meaning_bindings,
      generated_by_model,
    }) => {
      try {
        const result = await createSchemaField({
          schema_id: schema_id,
          name,
          field_type: fromAgentFieldType(field_type as AgentFieldType),
          sort_order,
          required,
          default_value,
          options,
          ref_schema_id: ref_schema_id,
          meaning_bindings: meaning_bindings as FieldMeaningBindingKey[] | undefined,
          generated_by_model,
        });
        emitChange({ type: 'schemaField', action: 'create', id: result.id });
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(toAgentSchemaField(result), null, 2) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  registerNetiorTool(
    server,
    'update_schema_field',
    {
      field_id: z.string().describe('The field ID to update'),
      name: z.string().optional().describe('New field name'),
      field_type: fieldTypeSchema.optional().describe('New field value type'),
      sort_order: z.number().optional().describe('New field order index'),
      required: z.boolean().optional().describe('Whether the field is required'),
      default_value: z.string().nullable().optional().describe('New default value'),
      options: z.string().nullable().optional().describe('New comma-separated inline options'),
      ref_schema_id: z.string().nullable().optional().describe('Referenced schema ID or null'),
      meaning_bindings: z.array(meaningBindingSchema).optional().describe('New semantic meaning bindings for this field'),
      generated_by_model: z.boolean().optional().describe('Whether this field was generated by a model'),
    },
    async ({
      field_id,
      name,
      field_type,
      sort_order,
      required,
      default_value,
      options,
      ref_schema_id,
      meaning_bindings,
      generated_by_model,
    }) => {
      try {
        const result = await updateSchemaField(field_id, {
          name,
          field_type: field_type ? fromAgentFieldType(field_type as AgentFieldType) : undefined,
          sort_order,
          required,
          default_value,
          options,
          ref_schema_id: ref_schema_id,
          meaning_bindings: meaning_bindings as FieldMeaningBindingKey[] | undefined,
          generated_by_model,
        });
        if (!result) {
          return {
            content: [{ type: 'text' as const, text: `Error: Schema field not found: ${field_id}` }],
            isError: true,
          };
        }
        emitChange({ type: 'schemaField', action: 'update', id: field_id });
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(toAgentSchemaField(result), null, 2) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  registerNetiorTool(
    server,
    'delete_schema_field',
    { field_id: z.string().describe('The field ID to delete') },
    async ({ field_id }) => {
      try {
        const deleted = await deleteSchemaField(field_id);
        if (!deleted) {
          return {
            content: [{ type: 'text' as const, text: `Error: Schema field not found: ${field_id}` }],
            isError: true,
          };
        }
        emitChange({ type: 'schemaField', action: 'delete', id: field_id });
        return {
          content: [{ type: 'text' as const, text: JSON.stringify({ success: true, id: field_id }) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  registerNetiorTool(
    server,
    'reorder_schema_fields',
    {
      schema_id: z.string().describe('The schema ID'),
      ordered_ids: z.array(z.string()).describe('Field IDs in the desired order'),
    },
    async ({ schema_id, ordered_ids }) => {
      try {
        const success = await reorderSchemaFields(schema_id, ordered_ids);
        return {
          content: [{ type: 'text' as const, text: JSON.stringify({ success, schema_id, ordered_ids }, null, 2) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );
}
